name: "[A] artifact/save-restore"

on:
  push:
    tags-ignore: ["*"]
    branches: ["master"]
    paths:
      - .github/workflows/act-artifact-save-restore.yaml

  workflow_dispatch:

jobs:
  save-files:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          echo "my custom file contents" > ./test-file-1.txt
          echo "" > ./test-file-2.txt
          echo "{}" > ./test-file-2.json
          mkdir "test-dir"
          echo "" > ./test-dir/test-file-3.txt
          echo "{}" > ./test-dir/test-file-3.json
          echo "" > ./test-file-4.bin

      - uses: milaboratory/github-ci/actions/artifact/save@v4-beta
        with:
          name: "build-txts"
          path: |
            **/*.txt

      - uses: milaboratory/github-ci/actions/artifact/save@v4-beta
        with:
          name: "build-jsons"
          path: |
            **/*.json

  restore-files:
    runs-on: ubuntu-latest

    needs:
      - save-files

    steps:
      - uses: milaboratory/github-ci/actions/artifact/restore@v4-beta
        with:
          pattern: build-*

      - uses: milaboratory/github-ci/actions/action-test@v1
        env:
          FILES_LIST_EXPECTED: |-
            ./test-dir/test-file-3.json
            ./test-dir/test-file-3.txt
            ./test-file-1.txt
            ./test-file-2.json
            ./test-file-2.txt

        with:
          test: |
            FILES_LIST_ACTUAL="$(find . -type f | grep -E '(.txt|.json)$' | sort)"

            test_equals "Restored artifacts" "${FILES_LIST_EXPECTED}" "${FILES_LIST_ACTUAL}"
