name: "[A] files/content"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-files-list.yaml

  workflow_dispatch:

jobs:
  test-list-files:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          echo "my custom file contents" > ./test-file.txt

      - id: list
        uses: milaboratory/github-ci/actions/files/list@v4-beta
        with:
          relative: true
          patterns: |
            **/*.txt

    outputs:
      content: ${{ steps.list.outputs.paths }}

  check:
    runs-on: ubuntu-latest

    needs:
      - test-list-files

    steps:
      - uses: milaboratory/github-ci/actions/action-test@v1
        env:
          CAT_LIST_EXPECTED: test-file.txt
          CAT_LIST_ACTUAL: ${{ needs.test-list-files.outputs.content }}

        with:
          test: |
            test_equals "List files" "${CAT_LIST_EXPECTED}" "${CAT_LIST_ACTUAL}"
