name: "[B] update-cdn-link/s3"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/blk-update-cdn-link.yaml

  workflow_dispatch:


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v2
      - id: context
        uses: milaboratory/github-ci/actions/context@v2

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}


  update-cdn-link:
    name: Update the latest build link on the CDN
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - id: cdn-string
        uses: milaboratory/github-ci/actions/shell@v2
        with:
          dump-stdout: false
          run: |
            CDN_URL=$(echo '["https://cdn.milaboratory.com/software/mixcr/mixcr-4.1.0-20-develop-a1cf9a3bcafe0055121eec1f855cdb91e12e0ea9.zip"]' | jq -r  -c '.[]')
            ghwa_set_output "converted_cdn_url" "${CDN_URL}"

      - id: cdn
        uses: milaboratory/github-ci/blocks/update-cdn-link@v2-beta
        with:
          cdn-redirect-link: ${{ fromJSON( steps.cdn-string.outputs.data ).converted_cdn_url }}
          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'

          s3-bucket-path: 'link/software/mixcr'
          s3-bucket-key: 'mixcr-test.zip'

