name: Dump Env

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/dump-env.yaml

  workflow_dispatch:

jobs:
  dump-env:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: Dump env vars
    steps:
      - shell: bash
        run: |
          env
          echo
          printf "PWD: %s\n" pwd
